module.exports = [
  // список стран из Википедии на 29 ноября 2017 года
  {
    "name": "Нидерланды",
    "fullname": "Королевство Нидерландов",
    "english": "Netherlands",
    "capital": "Амстердам",
    "capitalEn": "",
    "iso": "NL",
    "mok": "NLD",
    "location": "Европа",
    "locationPrecise": "Западная Европа"
  },
  {
    "name": "Андорра",
    "fullname": "Княжество Андорра",
    "english": "Andorra",
    "capital": "Андорра-ла-Велья",
    "capitalEn": "",
    "iso": "AD",
    "mok": "AND",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Греция",
    "fullname": "Греческая Республика",
    "english": "Greece",
    "capital": "Афины",
    "capitalEn": "",
    "iso": "GR",
    "mok": "GRC",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Сербия",
    "fullname": "Республика Сербия",
    "english": "Serbia",
    "capital": "Белград",
    "capitalEn": "",
    "iso": "RS",
    "mok": "SRB",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Германия",
    "fullname": "Федеративная Республика Германия",
    "english": "Germany",
    "capital": "Берлин",
    "capitalEn": "",
    "iso": "DE",
    "mok": "DEU",
    "location": "Европа",
    "locationPrecise": "Западная Европа"
  },
  {
    "name": "Швейцария",
    "fullname": "Швейцарская Конфедерация",
    "english": "Switzerland",
    "capital": "Берн",
    "capitalEn": "",
    "iso": "CH",
    "mok": "CHE",
    "location": "Европа",
    "locationPrecise": "Западная Европа"
  },
  {
    "name": "Словакия",
    "fullname": "Словацкая Республика",
    "english": "Slovakia",
    "capital": "Братислава",
    "capitalEn": "",
    "iso": "SK",
    "mok": "SVK",
    "location": "Европа",
    "locationPrecise": "Восточная Европа"
  },
  {
    "name": "Бельгия",
    "fullname": "Королевство Бельгии",
    "english": "Belgium",
    "capital": "Брюссель",
    "capitalEn": "",
    "iso": "BE",
    "mok": "BEL",
    "location": "Европа",
    "locationPrecise": "Западная Европа"
  },
  {
    "name": "Венгрия",
    "fullname": "Венгерская Республика",
    "english": "Hungary",
    "capital": "Будапешт",
    "capitalEn": "",
    "iso": "HU",
    "mok": "HUN",
    "location": "Европа",
    "locationPrecise": "Восточная Европа"
  },
  {
    "name": "Румыния",
    "fullname": " ",
    "english": "Romania",
    "capital": "Бухарест",
    "capitalEn": "",
    "iso": "RO",
    "mok": "ROU",
    "location": "Европа",
    "locationPrecise": "Восточная Европа"
  },
  {
    "name": "Лихтенштейн",
    "fullname": "Княжество Лихтенштейн",
    "english": "Liechtenstein",
    "capital": "Вадуц",
    "capitalEn": "",
    "iso": "LI",
    "mok": "LIE",
    "location": "Европа",
    "locationPrecise": "Западная Европа"
  },
  {
    "name": "Мальта",
    "fullname": "Республика Мальта",
    "english": "Malta",
    "capital": "Валлетта",
    "capitalEn": "",
    "iso": "MT",
    "mok": "MLT",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Польша",
    "fullname": "Республика Польша",
    "english": "Poland",
    "capital": "Варшава",
    "capitalEn": "",
    "iso": "PL",
    "mok": "POL",
    "location": "Европа",
    "locationPrecise": "Восточная Европа"
  },
  {
    "name": "Ватикан",
    "fullname": " ",
    "english": "Holy See (Vatican City State)",
    "capital": "Ватикан",
    "capitalEn": "",
    "iso": "VA",
    "mok": "VAT",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Австрия",
    "fullname": "Австрийская Республика",
    "english": "Austria",
    "capital": "Вена",
    "capitalEn": "",
    "iso": "AT",
    "mok": "AUT",
    "location": "Европа",
    "locationPrecise": "Западная Европа"
  },
  {
    "name": "Литва",
    "fullname": "Литовская Республика",
    "english": "Lithuania",
    "capital": "Вильнюс",
    "capitalEn": "",
    "iso": "LT",
    "mok": "LTU",
    "location": "Европа",
    "locationPrecise": "Северная Европа"
  },
  {
    "name": "Ирландия",
    "fullname": " ",
    "english": "Ireland",
    "capital": "Дублин",
    "capitalEn": "",
    "iso": "IE",
    "mok": "IRL",
    "location": "Европа",
    "locationPrecise": "Северная Европа"
  },
  {
    "name": "Хорватия",
    "fullname": "Республика Хорватия",
    "english": "Croatia",
    "capital": "Загреб",
    "capitalEn": "",
    "iso": "HR",
    "mok": "HRV",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Украина",
    "fullname": " ",
    "english": "Ukraine",
    "capital": "Киев",
    "capitalEn": "",
    "iso": "UA",
    "mok": "UKR",
    "location": "Европа",
    "locationPrecise": "Восточная Европа"
  },
  {
    "name": "Молдавия",
    "fullname": "Республика Молдова",
    "english": "Moldova",
    "capital": "Кининёв",
    "capitalEn": "",
    "iso": "MD",
    "mok": "MDA",
    "location": "Европа",
    "locationPrecise": "Восточная Европа"
  },
  {
    "name": "Дания",
    "fullname": "Королевство Дания",
    "english": "Denmark",
    "capital": "Копенгаген",
    "capitalEn": "",
    "iso": "DK",
    "mok": "DNK",
    "location": "Европа",
    "locationPrecise": "Северная Европа"
  },
  {
    "name": "Португалия",
    "fullname": "Португальская Республика",
    "english": "Portugal",
    "capital": "Лиссабон",
    "capitalEn": "",
    "iso": "PT",
    "mok": "PRT",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Великобритания",
    "fullname": "Соединенное Королевство Великобритании и Северной Ирландии",
    "english": "United Kingdom",
    "capital": "Лондон",
    "capitalEn": "",
    "iso": "GB",
    "mok": "GBR",
    "location": "Европа",
    "locationPrecise": "Северная Европа"
  },
  {
    "name": "Словения",
    "fullname": "Республика Словения",
    "english": "Slovenia",
    "capital": "Любляна",
    "capitalEn": "",
    "iso": "SI",
    "mok": "SVN",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Люксембург",
    "fullname": "Великое Герцогство Люксембург",
    "english": "Luxembourg",
    "capital": "Люксембург",
    "capitalEn": "",
    "iso": "LU",
    "mok": "LUX",
    "location": "Европа",
    "locationPrecise": "Западная Европа"
  },
  {
    "name": "Испания",
    "fullname": "Королевство Испания",
    "english": "Spain",
    "capital": "Мадрид",
    "capitalEn": "",
    "iso": "ES",
    "mok": "ESP",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Беларусь",
    "fullname": "Республика Беларусь",
    "english": "Belarus",
    "capital": "Минск",
    "capitalEn": "",
    "iso": "BY",
    "mok": "BLR",
    "location": "Европа",
    "locationPrecise": "Восточная Европа"
  },
  {
    "name": "Монако",
    "fullname": "Княжество Монако",
    "english": "Monaco",
    "capital": "Монако",
    "capitalEn": "",
    "iso": "MC",
    "mok": "MCO",
    "location": "Европа",
    "locationPrecise": "Западная Европа"
  },
  {
    "name": "Россия",
    "fullname": "Российская Федерация",
    "english": "Russian Federation",
    "capital": "Москва",
    "capitalEn": "",
    "iso": "RU",
    "mok": "RUS",
    "location": "Европа",
    "locationPrecise": "Восточная Европа"
  },
  {
    "name": "Норвегия",
    "fullname": "Королевство Норвегия",
    "english": "Norway",
    "capital": "Осло",
    "capitalEn": "",
    "iso": "NO",
    "mok": "NOR",
    "location": "Европа",
    "locationPrecise": "Северная Европа"
  },
  {
    "name": "Франция",
    "fullname": "Французская Республика",
    "english": "France",
    "capital": "Париж",
    "capitalEn": "",
    "iso": "FR",
    "mok": "FRA",
    "location": "Европа",
    "locationPrecise": "Западная Европа"
  },
  {
    "name": "Черногория",
    "fullname": "Республика Черногория",
    "english": "Montenegro",
    "capital": "Подгорица",
    "capitalEn": "",
    "iso": "ME",
    "mok": "MNE",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Чехия",
    "fullname": "Чешская Республика",
    "english": "Czech Republic",
    "capital": "Прага",
    "capitalEn": "",
    "iso": "CZ",
    "mok": "CZE",
    "location": "Европа",
    "locationPrecise": "Восточная Европа"
  },
  {
    "name": "Исландия",
    "fullname": "Республика Исландия",
    "english": "Iceland",
    "capital": "Рейкьявик",
    "capitalEn": "",
    "iso": "IS",
    "mok": "ISL",
    "location": "Европа",
    "locationPrecise": "Северная Европа"
  },
  {
    "name": "Латвия",
    "fullname": "Латвийская Республика",
    "english": "Latvia",
    "capital": "Рига",
    "capitalEn": "",
    "iso": "LV",
    "mok": "LVA",
    "location": "Европа",
    "locationPrecise": "Северная Европа"
  },
  {
    "name": "Италия",
    "fullname": "Итальянская Республика",
    "english": "Italy",
    "capital": "Рим",
    "capitalEn": "",
    "iso": "IT",
    "mok": "ITA",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Сан-Марино",
    "fullname": "Республика Сан-Марино",
    "english": "San Marino",
    "capital": "Сан-Марино",
    "capitalEn": "",
    "iso": "SM",
    "mok": "SMR",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Босния и\nГерцеговина",
    "fullname": " ",
    "english": "Bosnia and Herzegovina",
    "capital": "Сараево",
    "capitalEn": "",
    "iso": "BA",
    "mok": "BIH",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Македония",
    "fullname": "Республика Македония",
    "english": "Macedonia, The Former Yugoslav Republic Of",
    "capital": "Скопье",
    "capitalEn": "",
    "iso": "MK",
    "mok": "MKD",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Болгария",
    "fullname": "Республика Болгария",
    "english": "Bulgaria",
    "capital": "София",
    "capitalEn": "",
    "iso": "BG",
    "mok": "BGR",
    "location": "Европа",
    "locationPrecise": "Восточная Европа"
  },
  {
    "name": "Швеция",
    "fullname": "Королевство Швеция",
    "english": "Sweden",
    "capital": "Стокгольм",
    "capitalEn": "",
    "iso": "SE",
    "mok": "SWE",
    "location": "Европа",
    "locationPrecise": "Северная Европа"
  },
  {
    "name": "Эстония",
    "fullname": "Эстонская Республика",
    "english": "Estonia",
    "capital": "Таллин",
    "capitalEn": "",
    "iso": "EE",
    "mok": "EST",
    "location": "Европа",
    "locationPrecise": "Северная Европа"
  },
  {
    "name": "Албания",
    "fullname": "Республика Албания",
    "english": "Albania",
    "capital": "Тирана",
    "capitalEn": "",
    "iso": "AL",
    "mok": "ALB",
    "location": "Европа",
    "locationPrecise": "Южная Европа"
  },
  {
    "name": "Финляндия",
    "fullname": "Финляндская Республика",
    "english": "Finland",
    "capital": "Хельсинки",
    "capitalEn": "",
    "iso": "FI",
    "mok": "FIN",
    "location": "Европа",
    "locationPrecise": "Северная Европа"
  },
  {
    "name": "ОАЭ",
    "fullname": "Объединенные Арабские Эмираты",
    "english": "United Arab Emirates",
    "capital": "Абу-Даби",
    "capitalEn": "",
    "iso": "AE",
    "mok": "ARE",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Иордания",
    "fullname": "Иорданское Хашимитское Королевство",
    "english": "Jordan",
    "capital": "Амман",
    "capitalEn": "",
    "iso": "JO",
    "mok": "JOR",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Турция",
    "fullname": "Турецкая Республика",
    "english": "Turkey",
    "capital": "Анкара",
    "capitalEn": "",
    "iso": "TR",
    "mok": "TUR",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Казахстан",
    "fullname": "Республика Казахстан",
    "english": "Kazakhstan",
    "capital": "Астана",
    "capitalEn": "",
    "iso": "KZ",
    "mok": "KAZ",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Туркмения",
    "fullname": "Туркменистан",
    "english": "Turkmenistan",
    "capital": "Ашхабад",
    "capitalEn": "",
    "iso": "TM",
    "mok": "TKM",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Ирак",
    "fullname": "Республика Ирак",
    "english": "Iraq",
    "capital": "Багдад",
    "capitalEn": "",
    "iso": "IQ",
    "mok": "IRQ",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Азербайджан",
    "fullname": "Республика Азербайджан",
    "english": "Azerbaijan",
    "capital": "Баку",
    "capitalEn": "",
    "iso": "AZ",
    "mok": "AZE",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Таиланд",
    "fullname": "Королевство Таиланд",
    "english": "Thailand",
    "capital": "Бангкок",
    "capitalEn": "",
    "iso": "TH",
    "mok": "THA",
    "location": "Азия",
    "locationPrecise": "Юго-Восточная Азия"
  },
  {
    "name": "Бруней",
    "fullname": "Бруней-Даруссалам",
    "english": "Brunei Darussalam",
    "capital": "Бандар-Сери-Бегаван",
    "capitalEn": "",
    "iso": "BN",
    "mok": "BRN",
    "location": "Азия",
    "locationPrecise": "Юго-Восточная Азия"
  },
  {
    "name": "Ливан",
    "fullname": "Ливанская Республика",
    "english": "Lebanon",
    "capital": "Бейрут",
    "capitalEn": "",
    "iso": "LB",
    "mok": "LBN",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Киргизия",
    "fullname": "Киргизская Республика",
    "english": "Kyrgyzstan",
    "capital": "Бишкек",
    "capitalEn": "",
    "iso": "KG",
    "mok": "KGZ",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Лаос",
    "fullname": "Лаосская Народно-Демократическая Республика",
    "english": "Lao People's Democratic Republic",
    "capital": "Вьентьян",
    "capitalEn": "",
    "iso": "LA",
    "mok": "LAO",
    "location": "Азия",
    "locationPrecise": "Юго-Восточная Азия"
  },
  {
    "name": "Бангладеш",
    "fullname": "Народная Республика Бангладеш",
    "english": "Bangladesh",
    "capital": "Дакка",
    "capitalEn": "",
    "iso": "BD",
    "mok": "BGD",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Сирия",
    "fullname": "Сирийская Арабская Республика",
    "english": "Syrian Arab Republic",
    "capital": "Дамаск",
    "capitalEn": "",
    "iso": "SY",
    "mok": "SYR",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Индия",
    "fullname": "Республика Индия",
    "english": "India",
    "capital": "Дели",
    "capitalEn": "",
    "iso": "IN",
    "mok": "IND",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Индонезия",
    "fullname": "Республика Индонезия",
    "english": "Indonesia",
    "capital": "Джакарта",
    "capitalEn": "",
    "iso": "ID",
    "mok": "IDN",
    "location": "Азия",
    "locationPrecise": "Юго-Восточная Азия"
  },
  {
    "name": "Восточный\nТимор",
    "fullname": "Демократическая Республика Тимор-Лесте",
    "english": "Timor-Leste",
    "capital": "Дили",
    "capitalEn": "",
    "iso": "TL",
    "mok": "TLS",
    "location": "Азия",
    "locationPrecise": "Юго-Восточная Азия"
  },
  {
    "name": "Катар",
    "fullname": "Государство Катар",
    "english": "Qatar",
    "capital": "Доха",
    "capitalEn": "",
    "iso": "QA",
    "mok": "QAT",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Таджикистан",
    "fullname": "Республика Таджикистан",
    "english": "Tajikistan",
    "capital": "Душанбе",
    "capitalEn": "",
    "iso": "TJ",
    "mok": "TJK",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Армения",
    "fullname": "Республика Армения",
    "english": "Armenia",
    "capital": "Ереван",
    "capitalEn": "",
    "iso": "AM",
    "mok": "ARM",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Израиль",
    "fullname": "Государство Израиль",
    "english": "Israel",
    "capital": "Иерусалим",
    "capitalEn": "",
    "iso": "IL",
    "mok": "ISR",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Пакистан",
    "fullname": "Исламская Республика Пакистан",
    "english": "Pakistan",
    "capital": "Исламабад",
    "capitalEn": "",
    "iso": "PK",
    "mok": "PAK",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Афганистан",
    "fullname": "Переходное Исламское Государство Афганистан",
    "english": "Afghanistan",
    "capital": "Кабул",
    "capitalEn": "",
    "iso": "AF",
    "mok": "AFG",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Непал",
    "fullname": "Федеративная Демократическая Республика Непал",
    "english": "Nepal",
    "capital": "Катманду",
    "capitalEn": "",
    "iso": "NP",
    "mok": "NPL",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Малайзия",
    "fullname": " ",
    "english": "Malaysia",
    "capital": "Куала-Лумпур",
    "capitalEn": "",
    "iso": "MY",
    "mok": "MYS",
    "location": "Азия",
    "locationPrecise": "Юго-Восточная Азия"
  },
  {
    "name": "Мальдивы",
    "fullname": "Мальдивская Республика",
    "english": "Maldives",
    "capital": "Мале",
    "capitalEn": "",
    "iso": "MV",
    "mok": "MDV",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Бахрейн",
    "fullname": "Королевство Бахрейн",
    "english": "Bahrain",
    "capital": "Манама",
    "capitalEn": "",
    "iso": "BH",
    "mok": "BHR",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Филиппины",
    "fullname": "Республика Филиппины",
    "english": "Philippines",
    "capital": "Манила",
    "capitalEn": "",
    "iso": "PH",
    "mok": "PHL",
    "location": "Азия",
    "locationPrecise": "Юго-Восточная Азия"
  },
  {
    "name": "Оман",
    "fullname": "Султанат Оман",
    "english": "Oman",
    "capital": "Маскат",
    "capitalEn": "",
    "iso": "OM",
    "mok": "OMN",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Мьянма",
    "fullname": "Союз Мьянма",
    "english": "Myanmar",
    "capital": "Нейпьидо",
    "capitalEn": "",
    "iso": "MM",
    "mok": "MMR",
    "location": "Азия",
    "locationPrecise": "Юго-Восточная Азия"
  },
  {
    "name": "Кипр",
    "fullname": "Республика Кипр",
    "english": "Cyprus",
    "capital": "Никосия",
    "capitalEn": "",
    "iso": "CY",
    "mok": "CYP",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Китай",
    "fullname": "Китайская Народная Республика",
    "english": "China",
    "capital": "Пекин",
    "capitalEn": "",
    "iso": "CN",
    "mok": "CHN",
    "location": "Азия",
    "locationPrecise": "Восточная Азия"
  },
  {
    "name": "Камбоджа",
    "fullname": "Королевство Камбоджа",
    "english": "Cambodia",
    "capital": "Пномпень",
    "capitalEn": "",
    "iso": "KH",
    "mok": "KHM",
    "location": "Азия",
    "locationPrecise": "Юго-Восточная Азия"
  },
  {
    "name": "КНДР",
    "fullname": "Корейская Народно-Демократическая Республика",
    "english": "Korea, Democratic People's republic of",
    "capital": "Пхеньян",
    "capitalEn": "",
    "iso": "KP",
    "mok": "PRK",
    "location": "Азия",
    "locationPrecise": "Восточная Азия"
  },
  {
    "name": "Йемен",
    "fullname": "Йеменская Республика",
    "english": "Yemen",
    "capital": "Сана",
    "capitalEn": "",
    "iso": "YE",
    "mok": "YEM",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Республика\nКорея",
    "fullname": "Республика Корея",
    "english": "Korea, Republic of",
    "capital": "Сеул",
    "capitalEn": "",
    "iso": "KR",
    "mok": "KOR",
    "location": "Азия",
    "locationPrecise": "Восточная Азия"
  },
  {
    "name": "Сингапур",
    "fullname": "Республика Сингапур",
    "english": "Singapore",
    "capital": "Сингапур",
    "capitalEn": "",
    "iso": "SG",
    "mok": "SGP",
    "location": "Азия",
    "locationPrecise": "Юго-Восточная Азия"
  },
  {
    "name": "Узбекистан",
    "fullname": "Республика Узбекистан",
    "english": "Uzbekistan",
    "capital": "Ташкент",
    "capitalEn": "",
    "iso": "UZ",
    "mok": "UZB",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Грузия",
    "fullname": " ",
    "english": "Georgia",
    "capital": "Тбилиси",
    "capitalEn": "",
    "iso": "GE",
    "mok": "GEO",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Иран",
    "fullname": "Исламская Республика Иран",
    "english": "Iran, Islamic Republic of",
    "capital": "Тегеран",
    "capitalEn": "",
    "iso": "IR",
    "mok": "IRN",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Япония",
    "fullname": " ",
    "english": "Japan",
    "capital": "Токио",
    "capitalEn": "",
    "iso": "JP",
    "mok": "JPN",
    "location": "Азия",
    "locationPrecise": "Восточная Азия"
  },
  {
    "name": "Бутан",
    "fullname": "Королевство Бутан",
    "english": "Bhutan",
    "capital": "Тхимпху",
    "capitalEn": "",
    "iso": "BT",
    "mok": "BTN",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Монголия",
    "fullname": " ",
    "english": "Mongolia",
    "capital": "Улан-Батор",
    "capitalEn": "",
    "iso": "MN",
    "mok": "MNG",
    "location": "Азия",
    "locationPrecise": "Восточная Азия"
  },
  {
    "name": "Вьетнам",
    "fullname": "Социалистическая Республика Вьетнам",
    "english": "Vietnam",
    "capital": "Ханой",
    "capitalEn": "",
    "iso": "VN",
    "mok": "VNM",
    "location": "Азия",
    "locationPrecise": "Юго-Восточная Азия"
  },
  {
    "name": "Шри-Ланка",
    "fullname": "Демократическая Социалистическая Республика Шри-Ланка",
    "english": "Sri Lanka",
    "capital": "Шри-Джаяварденепура-Котте",
    "capitalEn": "",
    "iso": "LK",
    "mok": "LKA",
    "location": "Азия",
    "locationPrecise": "Южная часть Центральной Азии"
  },
  {
    "name": "Кувейт",
    "fullname": "Государство Кувейт",
    "english": "Kuwait",
    "capital": "Эль-Кувейт",
    "capitalEn": "",
    "iso": "KW",
    "mok": "KWT",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Саудовская\nАравия",
    "fullname": "Королевство Саудовская Аравия",
    "english": "Saudi Arabia",
    "capital": "Эр-Рияд",
    "capitalEn": "",
    "iso": "SA",
    "mok": "SAU",
    "location": "Азия",
    "locationPrecise": "Западная Азия"
  },
  {
    "name": "Нигерия",
    "fullname": "Федеративная Республика Нигерия",
    "english": "Nigeria",
    "capital": "Абуджа",
    "capitalEn": "",
    "iso": "NG",
    "mok": "NGA",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Эфиопия",
    "fullname": "Федеративная Демократическая Республика Эфиопия",
    "english": "Ethiopia",
    "capital": "Аддис-Абеба",
    "capitalEn": "",
    "iso": "ET",
    "mok": "ETH",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Гана",
    "fullname": "Республика Гана",
    "english": "Ghana",
    "capital": "Аккра",
    "capitalEn": "",
    "iso": "GH",
    "mok": "GHA",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Алжир",
    "fullname": "Алжирская Народная Демократическая Республика",
    "english": "Algeria",
    "capital": "Алжир",
    "capitalEn": "",
    "iso": "DZ",
    "mok": "DZA",
    "location": "Африка",
    "locationPrecise": "Северная Африка"
  },
  {
    "name": "Мадагаскар",
    "fullname": "Республика Мадагаскар",
    "english": "Madagascar",
    "capital": "Антананариву",
    "capitalEn": "",
    "iso": "MG",
    "mok": "MDG",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Эритрея",
    "fullname": " ",
    "english": "Eritrea",
    "capital": "Асмэра",
    "capitalEn": "",
    "iso": "ER",
    "mok": "ERI",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Мали",
    "fullname": "Республика Мали",
    "english": "Mali",
    "capital": "Бамако",
    "capitalEn": "",
    "iso": "ML",
    "mok": "MLI",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "ЦАР",
    "fullname": "Центрально-Африканская Республика",
    "english": "Central African Republic",
    "capital": "Банги",
    "capitalEn": "",
    "iso": "CF",
    "mok": "CAF",
    "location": "Африка",
    "locationPrecise": "Центральная Африка"
  },
  {
    "name": "Гамбия",
    "fullname": "Республика Гамбия",
    "english": "Gambia",
    "capital": "Банжул",
    "capitalEn": "",
    "iso": "GM",
    "mok": "GMB",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Гвинея",
    "fullname": "Гвинейская Республика",
    "english": "Guinea",
    "capital": "Конакри",
    "capitalEn": "",
    "iso": "GN",
    "mok": "GIN",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Гвинея-Бисау",
    "fullname": "Республика Гвинея-Бисау",
    "english": "Guinea-Bissau",
    "capital": "Бисау",
    "capitalEn": "",
    "iso": "GW",
    "mok": "GNB",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Конго",
    "fullname": "Республика Конго",
    "english": "Congo",
    "capital": "Браззавиль",
    "capitalEn": "",
    "iso": "CG",
    "mok": "COG",
    "location": "Африка",
    "locationPrecise": "Центральная Африка"
  },
  {
    "name": "Конго,\nДем. Респ.",
    "fullname": "Демократическая Республика Конго",
    "english": "Congo, Democratic Republic of the",
    "capital": "Киншаса",
    "capitalEn": "",
    "iso": "CD",
    "mok": "COD",
    "location": "Африка",
    "locationPrecise": "Центральная Африка"
  },
  {
    "name": "Бурунди",
    "fullname": "Республика Бурунди",
    "english": "Burundi",
    "capital": "Бужумбура",
    "capitalEn": "",
    "iso": "BI",
    "mok": "BDI",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Сейшелы",
    "fullname": "Республика Сейшелы",
    "english": "Seychelles",
    "capital": "Виктория",
    "capitalEn": "",
    "iso": "SC",
    "mok": "SYC",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Намибия",
    "fullname": "Республика Намибия",
    "english": "Namibia",
    "capital": "Виндхук",
    "capitalEn": "",
    "iso": "NA",
    "mok": "NAM",
    "location": "Африка",
    "locationPrecise": "Южная часть Африки"
  },
  {
    "name": "Ботсвана",
    "fullname": "Республика Ботсвана",
    "english": "Botswana",
    "capital": "Габороне",
    "capitalEn": "",
    "iso": "BW",
    "mok": "BWA",
    "location": "Африка",
    "locationPrecise": "Южная часть Африки"
  },
  {
    "name": "Сенегал",
    "fullname": "Республика Сенегал",
    "english": "Senegal",
    "capital": "Дакар",
    "capitalEn": "",
    "iso": "SN",
    "mok": "SEN",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Джибути",
    "fullname": "Республика Джибути",
    "english": "Djibouti",
    "capital": "Джибути",
    "capitalEn": "",
    "iso": "DJ",
    "mok": "DJI",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Южный Судан",
    "fullname": " ",
    "english": "South Sudan",
    "capital": "Джуба",
    "capitalEn": "",
    "iso": "SS",
    "mok": "SSD",
    "location": "Африка",
    "locationPrecise": "Северная Африка"
  },
  {
    "name": "Танзания",
    "fullname": "Объединенная Республика Танзания",
    "english": "Tanzania, United Republic Of",
    "capital": "Додома",
    "capitalEn": "",
    "iso": "TZ",
    "mok": "TZA",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Египет",
    "fullname": "Арабская Республика Египет",
    "english": "Egypt",
    "capital": "Каир",
    "capitalEn": "",
    "iso": "EG",
    "mok": "EGY",
    "location": "Африка",
    "locationPrecise": "Северная Африка"
  },
  {
    "name": "Уганда",
    "fullname": "Республика Уганда",
    "english": "Uganda",
    "capital": "Кампала",
    "capitalEn": "",
    "iso": "UG",
    "mok": "UGA",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Руанда",
    "fullname": "Руандийская Республика",
    "english": "Rwanda",
    "capital": "Кигали",
    "capitalEn": "",
    "iso": "RW",
    "mok": "RWA",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Габон",
    "fullname": "Габонская Республика",
    "english": "Gabon",
    "capital": "Либревиль",
    "capitalEn": "",
    "iso": "GA",
    "mok": "GAB",
    "location": "Африка",
    "locationPrecise": "Центральная Африка"
  },
  {
    "name": "Малави",
    "fullname": "Республика Малави",
    "english": "Malawi",
    "capital": "Лилонгве",
    "capitalEn": "",
    "iso": "MW",
    "mok": "MWI",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Того",
    "fullname": "Тоголезская Республика",
    "english": "Togo",
    "capital": "Ломе",
    "capitalEn": "",
    "iso": "TG",
    "mok": "TGO",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Ангола",
    "fullname": "Республика Ангола",
    "english": "Angola",
    "capital": "Луанда",
    "capitalEn": "",
    "iso": "AO",
    "mok": "AGO",
    "location": "Африка",
    "locationPrecise": "Центральная Африка"
  },
  {
    "name": "Замбия",
    "fullname": "Республика Замбия",
    "english": "Zambia",
    "capital": "Лусака",
    "capitalEn": "",
    "iso": "ZM",
    "mok": "ZMB",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Экваториальная\nГвинея",
    "fullname": "Республика Экваториальная Гвинея",
    "english": "Equatorial Guinea",
    "capital": "Малабо",
    "capitalEn": "",
    "iso": "GQ",
    "mok": "GNQ",
    "location": "Африка",
    "locationPrecise": "Центральная Африка"
  },
  {
    "name": "Мозамбик",
    "fullname": "Республика Мозамбик",
    "english": "Mozambique",
    "capital": "Мапуту",
    "capitalEn": "",
    "iso": "MZ",
    "mok": "MOZ",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Лесото",
    "fullname": "Королевство Лесото",
    "english": "Lesotho",
    "capital": "Масеру",
    "capitalEn": "",
    "iso": "LS",
    "mok": "LSO",
    "location": "Африка",
    "locationPrecise": "Южная часть Африки"
  },
  {
    "name": "Свазиленд",
    "fullname": "Королевство Свазиленд",
    "english": "Swaziland",
    "capital": "Мбабане",
    "capitalEn": "",
    "iso": "SZ",
    "mok": "SWZ",
    "location": "Африка",
    "locationPrecise": "Южная часть Африки"
  },
  {
    "name": "Сомали",
    "fullname": "Сомалийская Республика",
    "english": "Somalia",
    "capital": "Могадишо",
    "capitalEn": "",
    "iso": "SO",
    "mok": "SOM",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Либерия",
    "fullname": "Республика Либерия",
    "english": "Liberia",
    "capital": "Монровия",
    "capitalEn": "",
    "iso": "LR",
    "mok": "LBR",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Коморы",
    "fullname": "Союз Коморы",
    "english": "Comoros",
    "capital": "Морони",
    "capitalEn": "",
    "iso": "KM",
    "mok": "COM",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Кения",
    "fullname": "Республика Кения",
    "english": "Kenya",
    "capital": "Найроби",
    "capitalEn": "",
    "iso": "KE",
    "mok": "KEN",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Чад",
    "fullname": "Республика Чад",
    "english": "Chad",
    "capital": "Нджамена",
    "capitalEn": "",
    "iso": "TD",
    "mok": "TCD",
    "location": "Африка",
    "locationPrecise": "Центральная Африка"
  },
  {
    "name": "Нигер",
    "fullname": "Республика Нигер",
    "english": "Niger",
    "capital": "Ниамей",
    "capitalEn": "",
    "iso": "NE",
    "mok": "NER",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Мавритания",
    "fullname": "Исламская Республика Мавритания",
    "english": "Mauritania",
    "capital": "Нуакшот",
    "capitalEn": "",
    "iso": "MR",
    "mok": "MRT",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Маврикий",
    "fullname": "Республика Маврикий",
    "english": "Mauritius",
    "capital": "Порт-Луи",
    "capitalEn": "",
    "iso": "MU",
    "mok": "MUS",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Бенин",
    "fullname": "Республика Бенин",
    "english": "Benin",
    "capital": "Порто-Ново",
    "capitalEn": "",
    "iso": "BJ",
    "mok": "BEN",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Кабо-Верде",
    "fullname": "Республика Кабо-Верде",
    "english": "Cape Verde",
    "capital": "Прая",
    "capitalEn": "",
    "iso": "CV",
    "mok": "CPV",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "ЮАР",
    "fullname": "Южно-Африканская Республика",
    "english": "South Africa",
    "capital": "Претория",
    "capitalEn": "",
    "iso": "ZA",
    "mok": "ZAF",
    "location": "Африка",
    "locationPrecise": "Южная часть Африки"
  },
  {
    "name": "Марокко",
    "fullname": "Королевство Марокко",
    "english": "Morocco",
    "capital": "Рабат",
    "capitalEn": "",
    "iso": "MA",
    "mok": "MAR",
    "location": "Африка",
    "locationPrecise": "Северная Африка"
  },
  {
    "name": "Сан-Томе и\nПринсипи",
    "fullname": "Демократическая Республика Сан-Томе и Принсипи",
    "english": "Sao Tome and Principe",
    "capital": "Сан-Томе",
    "capitalEn": "",
    "iso": "ST",
    "mok": "STP",
    "location": "Африка",
    "locationPrecise": "Центральная Африка"
  },
  {
    "name": "Ливия",
    "fullname": "",
    "english": "",
    "capital": "Триполи",
    "capitalEn": "",
    "iso": "LY",
    "mok": "LBA",
"location": "Африка",
    "locationPrecise": "Северная Африка"
  },
  {
    "name": "Тунис",
    "fullname": "Тунисская Республика",
    "english": "Tunisia",
    "capital": "Тунис",
    "capitalEn": "",
    "iso": "TN",
    "mok": "TUN",
    "location": "Африка",
    "locationPrecise": "Северная Африка"
  },
  {
    "name": "Буркина-Фасо",
    "fullname": " ",
    "english": "Burkina Faso",
    "capital": "Уагадугу",
    "capitalEn": "",
    "iso": "BF",
    "mok": "BFA",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Сьерра-Леоне",
    "fullname": "Республика Сьерра-Леоне",
    "english": "Sierra Leone",
    "capital": "Фритаун",
    "capitalEn": "",
    "iso": "SL",
    "mok": "SLE",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Зимбабве",
    "fullname": "Республика Зимбабве",
    "english": "Zimbabwe",
    "capital": "Хараре",
    "capitalEn": "",
    "iso": "ZW",
    "mok": "ZWE",
    "location": "Африка",
    "locationPrecise": "Восточная Африка"
  },
  {
    "name": "Судан",
    "fullname": "Республика Судан",
    "english": "Sudan",
    "capital": "Хартум",
    "capitalEn": "",
    "iso": "SD",
    "mok": "SDN",
    "location": "Африка",
    "locationPrecise": "Северная Африка"
  },
  {
    "name": "Кот д'Ивуар",
    "fullname": "Республика Кот д'Ивуар",
    "english": "Cote d'Ivoire",
    "capital": "Ямусукро",
    "capitalEn": "",
    "iso": "CI",
    "mok": "CIV",
    "location": "Африка",
    "locationPrecise": "Западная Африка"
  },
  {
    "name": "Камерун",
    "fullname": "Республика Камерун",
    "english": "Cameroon",
    "capital": "Яунде",
    "capitalEn": "",
    "iso": "CM",
    "mok": "CMR",
    "location": "Африка",
    "locationPrecise": "Центральная Африка"
  },
  {
    "name": "Парагвай",
    "fullname": "Республика Парагвай",
    "english": "Paraguay",
    "capital": "Асунсьон",
    "capitalEn": "",
    "iso": "PY",
    "mok": "PRY",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "Сент-Китс\nи Невис",
    "fullname": " ",
    "english": "Saint Kitts and Nevis",
    "capital": "Бастер",
    "capitalEn": "",
    "iso": "KN",
    "mok": "KNA",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Белиз",
    "fullname": " ",
    "english": "Belize",
    "capital": "Бельмопан",
    "capitalEn": "",
    "iso": "BZ",
    "mok": "BLZ",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Колумбия",
    "fullname": "Республика Колумбия",
    "english": "Colombia",
    "capital": "Богота",
    "capitalEn": "",
    "iso": "CO",
    "mok": "COL",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "Бразилия",
    "fullname": "Федеративная Республика Бразилия",
    "english": "Brazil",
    "capital": "Бразилиа",
    "capitalEn": "",
    "iso": "BR",
    "mok": "BRA",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "Барбадос",
    "fullname": " ",
    "english": "Barbados",
    "capital": "Бриджтаун",
    "capitalEn": "",
    "iso": "BB",
    "mok": "BRB",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Аргентина",
    "fullname": "Аргентинская Республика",
    "english": "Argentina",
    "capital": "Буэнос-Айрес",
    "capitalEn": "",
    "iso": "AR",
    "mok": "ARG",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "США",
    "fullname": "Соединенные Штаты Америки",
    "english": "United States",
    "capital": "Вашингтон",
    "capitalEn": "",
    "iso": "US",
    "mok": "USA",
    "location": "Америка",
    "locationPrecise": "Северная Америка"
  },
  {
    "name": "Куба",
    "fullname": "Республика Куба",
    "english": "Cuba",
    "capital": "Гавана",
    "capitalEn": "",
    "iso": "CU",
    "mok": "CUB",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Гватемала",
    "fullname": "Республика Гватемала",
    "english": "Guatemala",
    "capital": "Гватемала",
    "capitalEn": "",
    "iso": "GT",
    "mok": "GTM",
    "location": "Америка",
    "locationPrecise": "Центральная Америка"
  },
  {
    "name": "Гайана",
    "fullname": "Республика Гайана",
    "english": "Guyana",
    "capital": "Джорджтаун",
    "capitalEn": "",
    "iso": "GY",
    "mok": "GUY",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "Венесуэла",
    "fullname": "Боливарийская Республика Венесуэла",
    "english": "Venezuela",
    "capital": "Каракас",
    "capitalEn": "",
    "iso": "VE",
    "mok": "VEN",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "Сент-Люсия",
    "fullname": " ",
    "english": "Saint Lucia",
    "capital": "Кастри",
    "capitalEn": "",
    "iso": "LC",
    "mok": "LCA",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Сент-Винсент\nи Гренадины",
    "fullname": " ",
    "english": "Saint Vincent and the Grenadines",
    "capital": "Кингстаун",
    "capitalEn": "",
    "iso": "VC",
    "mok": "VCT",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Ямайка",
    "fullname": " ",
    "english": "Jamaica",
    "capital": "Кингстон",
    "capitalEn": "",
    "iso": "JM",
    "mok": "JAM",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Эквадор",
    "fullname": "Республика Эквадор",
    "english": "Ecuador",
    "capital": "Кито",
    "capitalEn": "",
    "iso": "EC",
    "mok": "ECU",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "Перу",
    "fullname": "Республика Перу",
    "english": "Peru",
    "capital": "Лима",
    "capitalEn": "",
    "iso": "PE",
    "mok": "PER",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "Никарагуа",
    "fullname": "Республика Никарагуа",
    "english": "Nicaragua",
    "capital": "Манагуа",
    "capitalEn": "",
    "iso": "NI",
    "mok": "NIC",
    "location": "Америка",
    "locationPrecise": "Центральная Америка"
  },
  {
    "name": "Мексика",
    "fullname": "Мексиканские Соединенные Штаты",
    "english": "Mexico",
    "capital": "Мехико",
    "capitalEn": "",
    "iso": "MX",
    "mok": "MEX",
    "location": "Америка",
    "locationPrecise": "Центральная Америка"
  },
  {
    "name": "Уругвай",
    "fullname": "Восточная Республика Уругвай",
    "english": "Uruguay",
    "capital": "Монтевидео",
    "capitalEn": "",
    "iso": "UY",
    "mok": "URY",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "Багамы",
    "fullname": "Содружество Багамы",
    "english": "Bahamas",
    "capital": "Нассау",
    "capitalEn": "",
    "iso": "BS",
    "mok": "BHS",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Канада",
    "fullname": " ",
    "english": "Canada",
    "capital": "Оттава",
    "capitalEn": "",
    "iso": "CA",
    "mok": "CAN",
    "location": "Америка",
    "locationPrecise": "Северная Америка"
  },
  {
    "name": "Панама",
    "fullname": "Республика Панама",
    "english": "Panama",
    "capital": "Панама",
    "capitalEn": "",
    "iso": "PA",
    "mok": "PAN",
    "location": "Америка",
    "locationPrecise": "Центральная Америка"
  },
  {
    "name": "Суринам",
    "fullname": "Республика Суринам",
    "english": "Suriname",
    "capital": "Парамарибо",
    "capitalEn": "",
    "iso": "SR",
    "mok": "SUR",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "Гаити",
    "fullname": "Республика Гаити",
    "english": "Haiti",
    "capital": "Порт-о-Пренс",
    "capitalEn": "",
    "iso": "HT",
    "mok": "HTI",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Тринидад\nи Тобаго",
    "fullname": "Республика Тринидад и Тобаго",
    "english": "Trinidad and Tobago",
    "capital": "Порт-оф-Спейн",
    "capitalEn": "",
    "iso": "TT",
    "mok": "TTO",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Доминика",
    "fullname": "Содружество Доминики",
    "english": "Dominica",
    "capital": "Розо",
    "capitalEn": "",
    "iso": "DM",
    "mok": "DMA",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Сальвадор",
    "fullname": "Республика Эль-Сальвадор",
    "english": "El Salvador",
    "capital": "Сан-Сальвадор",
    "capitalEn": "",
    "iso": "SV",
    "mok": "SLV",
    "location": "Америка",
    "locationPrecise": "Центральная Америка"
  },
  {
    "name": "Коста-Рика",
    "fullname": "Республика Коста-Рика",
    "english": "Costa Rica",
    "capital": "Сан-Хосе",
    "capitalEn": "",
    "iso": "CR",
    "mok": "CRI",
    "location": "Америка",
    "locationPrecise": "Центральная Америка"
  },
  {
    "name": "Доминиканская\nРеспублика",
    "fullname": " ",
    "english": "Dominican Republic",
    "capital": "Санто-Доминго",
    "capitalEn": "",
    "iso": "DO",
    "mok": "DOM",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Чили",
    "fullname": "Республика Чили",
    "english": "Chile",
    "capital": "Сантьяго",
    "capitalEn": "",
    "iso": "CL",
    "mok": "CHL",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "Антигуа\nи Барбуда",
    "fullname": " ",
    "english": "Antigua and Barbuda",
    "capital": "Сент-Джонс",
    "capitalEn": "",
    "iso": "AG",
    "mok": "ATG",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Гренада",
    "fullname": " ",
    "english": "Grenada",
    "capital": "Сент-Джорджес",
    "capitalEn": "",
    "iso": "GD",
    "mok": "GRD",
    "location": "Америка",
    "locationPrecise": "Карибский бассейн"
  },
  {
    "name": "Боливия",
    "fullname": "Многонациональное Государство Боливия",
    "english": "Bolivia, plurinational state of",
    "capital": "Сукре",
    "capitalEn": "",
    "iso": "BO",
    "mok": "BOL",
    "location": "Америка",
    "locationPrecise": "Южная Америка"
  },
  {
    "name": "Гондурас",
    "fullname": "Республика Гондурас",
    "english": "Honduras",
    "capital": "Тегусигальпа",
    "capitalEn": "",
    "iso": "HN",
    "mok": "HND",
    "location": "Америка",
    "locationPrecise": "Центральная Америка"
  },
  {
    "name": "Самоа",
    "fullname": "Независимое Государство Самоа",
    "english": "Samoa",
    "capital": "Апиа",
    "capitalEn": "",
    "iso": "WS",
    "mok": "WSM",
    "location": "Океания",
    "locationPrecise": "Полинезия"
  },
  {
    "name": "Новая Зеландия",
    "fullname": " ",
    "english": "New Zealand",
    "capital": "Веллингтон",
    "capitalEn": "",
    "iso": "NZ",
    "mok": "NZL",
    "location": "Океания",
    "locationPrecise": "Австралия и Новая Зеландия"
  },
  {
    "name": "Австралия",
    "fullname": " ",
    "english": "Australia",
    "capital": "Канберра",
    "capitalEn": "",
    "iso": "AU",
    "mok": "AUS",
    "location": "Океания",
    "locationPrecise": "Австралия и Новая Зеландия"
  },
  {
    "name": "Маршалловы\nострова",
    "fullname": "Республика Маршалловы острова",
    "english": "Marshall Islands",
    "capital": "Маджуро",
    "capitalEn": "",
    "iso": "MH",
    "mok": "MHL",
    "location": "Океания",
    "locationPrecise": "Микронезия"
  },
  {
    "name": "Палау",
    "fullname": "Республика Палау",
    "english": "Palau",
    "capital": "Нгерулмуд",
    "capitalEn": "",
    "iso": "PW",
    "mok": "PLW",
    "location": "Океания",
    "locationPrecise": "Микронезия"
  },
  {
    "name": "Тонга",
    "fullname": "Королевство Тонга",
    "english": "Tonga",
    "capital": "Нукуалофа",
    "capitalEn": "",
    "iso": "TO",
    "mok": "TON",
    "location": "Океания",
    "locationPrecise": "Полинезия"
  },
  {
    "name": "Микронезия",
    "fullname": "Федеративные штаты Микронезии",
    "english": "Micronesia, Federated States of",
    "capital": "Паликир",
    "capitalEn": "",
    "iso": "FM",
    "mok": "FSM",
    "location": "Океания",
    "locationPrecise": "Микронезия"
  },
  {
    "name": "Вануату",
    "fullname": "Республика Вануату",
    "english": "Vanuatu",
    "capital": "Порт-Вила",
    "capitalEn": "",
    "iso": "VU",
    "mok": "VUT",
    "location": "Океания",
    "locationPrecise": "Меланезия"
  },
  {
    "name": "Папуа-Новая\nГвинея",
    "fullname": " ",
    "english": "Papua New Guinea",
    "capital": "Порт-Морсби",
    "capitalEn": "",
    "iso": "PG",
    "mok": "PNG",
    "location": "Океания",
    "locationPrecise": "Меланезия"
  },
  {
    "name": "Фиджи",
    "fullname": "Республика островов Фиджи",
    "english": "Fiji",
    "capital": "Сува",
    "capitalEn": "",
    "iso": "FJ",
    "mok": "FJI",
    "location": "Океания",
    "locationPrecise": "Меланезия"
  },
  {
    "name": "Тувалу",
    "fullname": " ",
    "english": "Tuvalu",
    "capital": "Фунафути",
    "capitalEn": "",
    "iso": "TV",
    "mok": "TUV",
    "location": "Океания",
    "locationPrecise": "Полинезия"
  },
  {
    "name": "Соломоновы\nострова",
    "fullname": " ",
    "english": "Solomon Islands",
    "capital": "Хониара",
    "capitalEn": "",
    "iso": "SB",
    "mok": "SLB",
    "location": "Океания",
    "locationPrecise": "Меланезия"
  },
  {
    "name": "Кирибати",
    "fullname": "Республика Кирибати",
    "english": "Kiribati",
    "capital": "Южная Тарава",
    "capitalEn": "",
    "iso": "KI",
    "mok": "KIR",
    "location": "Океания",
    "locationPrecise": "Микронезия"
  },
  {
    "name": "Науру",
    "fullname": "Республика Науру",
    "english": "Nauru",
    "capital": "Офиц. столицы нет",
    "capitalEn": "",
    "iso": "NR",
    "mok": "NRU",
    "location": "Океания",
    "locationPrecise": "Микронезия"
  },
];
