module.exports = [
  // список стран из Википедии на 29 ноября 2017 года
  {
    "name": "Нидерланды",
    "fullname": "Королевство Нидерландов",
    "english": "Netherlands",
    "capital": "Амстердам",
    "capital-en": "",
    "alpha2": "NL",
    "alpha3": "NLD",
    "iso": "528",
    "location": "Европа",
    "location-precise": "Западная Европа"
  },
  {
    "name": "Андорра",
    "fullname": "Княжество Андорра",
    "english": "Andorra",
    "capital": "Андорра-ла-Велья",
    "capital-en": "",
    "alpha2": "AD",
    "alpha3": "AND",
    "iso": "020",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Греция",
    "fullname": "Греческая Республика",
    "english": "Greece",
    "capital": "Афины",
    "capital-en": "",
    "alpha2": "GR",
    "alpha3": "GRC",
    "iso": "300",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Сербия",
    "fullname": "Республика Сербия",
    "english": "Serbia",
    "capital": "Белград",
    "capital-en": "",
    "alpha2": "RS",
    "alpha3": "SRB",
    "iso": "688",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Германия",
    "fullname": "Федеративная Республика Германия",
    "english": "Germany",
    "capital": "Берлин",
    "capital-en": "",
    "alpha2": "DE",
    "alpha3": "DEU",
    "iso": "276",
    "location": "Европа",
    "location-precise": "Западная Европа"
  },
  {
    "name": "Швейцария",
    "fullname": "Швейцарская Конфедерация",
    "english": "Switzerland",
    "capital": "Берн",
    "capital-en": "",
    "alpha2": "CH",
    "alpha3": "CHE",
    "iso": "756",
    "location": "Европа",
    "location-precise": "Западная Европа"
  },
  {
    "name": "Словакия",
    "fullname": "Словацкая Республика",
    "english": "Slovakia",
    "capital": "Братислава",
    "capital-en": "",
    "alpha2": "SK",
    "alpha3": "SVK",
    "iso": "703",
    "location": "Европа",
    "location-precise": "Восточная Европа"
  },
  {
    "name": "Бельгия",
    "fullname": "Королевство Бельгии",
    "english": "Belgium",
    "capital": "Брюссель",
    "capital-en": "",
    "alpha2": "BE",
    "alpha3": "BEL",
    "iso": "056",
    "location": "Европа",
    "location-precise": "Западная Европа"
  },
  {
    "name": "Венгрия",
    "fullname": "Венгерская Республика",
    "english": "Hungary",
    "capital": "Будапешт",
    "capital-en": "",
    "alpha2": "HU",
    "alpha3": "HUN",
    "iso": "348",
    "location": "Европа",
    "location-precise": "Восточная Европа"
  },
  {
    "name": "Румыния",
    "fullname": " ",
    "english": "Romania",
    "capital": "Бухарест",
    "capital-en": "",
    "alpha2": "RO",
    "alpha3": "ROU",
    "iso": "642",
    "location": "Европа",
    "location-precise": "Восточная Европа"
  },
  {
    "name": "Лихтенштейн",
    "fullname": "Княжество Лихтенштейн",
    "english": "Liechtenstein",
    "capital": "Вадуц",
    "capital-en": "",
    "alpha2": "LI",
    "alpha3": "LIE",
    "iso": "438",
    "location": "Европа",
    "location-precise": "Западная Европа"
  },
  {
    "name": "Мальта",
    "fullname": "Республика Мальта",
    "english": "Malta",
    "capital": "Валлетта",
    "capital-en": "",
    "alpha2": "MT",
    "alpha3": "MLT",
    "iso": "470",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Польша",
    "fullname": "Республика Польша",
    "english": "Poland",
    "capital": "Варшава",
    "capital-en": "",
    "alpha2": "PL",
    "alpha3": "POL",
    "iso": "616",
    "location": "Европа",
    "location-precise": "Восточная Европа"
  },
  {
    "name": "Ватикан",
    "fullname": " ",
    "english": "Holy See (Vatican City State)",
    "capital": "Ватикан",
    "capital-en": "",
    "alpha2": "VA",
    "alpha3": "VAT",
    "iso": "336",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Австрия",
    "fullname": "Австрийская Республика",
    "english": "Austria",
    "capital": "Вена",
    "capital-en": "",
    "alpha2": "AT",
    "alpha3": "AUT",
    "iso": "040",
    "location": "Европа",
    "location-precise": "Западная Европа"
  },
  {
    "name": "Литва",
    "fullname": "Литовская Республика",
    "english": "Lithuania",
    "capital": "Вильнюс",
    "capital-en": "",
    "alpha2": "LT",
    "alpha3": "LTU",
    "iso": "440",
    "location": "Европа",
    "location-precise": "Северная Европа"
  },
  {
    "name": "Ирландия",
    "fullname": " ",
    "english": "Ireland",
    "capital": "Дублин",
    "capital-en": "",
    "alpha2": "IE",
    "alpha3": "IRL",
    "iso": "372",
    "location": "Европа",
    "location-precise": "Северная Европа"
  },
  {
    "name": "Хорватия",
    "fullname": "Республика Хорватия",
    "english": "Croatia",
    "capital": "Загреб",
    "capital-en": "",
    "alpha2": "HR",
    "alpha3": "HRV",
    "iso": "191",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Украина",
    "fullname": " ",
    "english": "Ukraine",
    "capital": "Киев",
    "capital-en": "",
    "alpha2": "UA",
    "alpha3": "UKR",
    "iso": "804",
    "location": "Европа",
    "location-precise": "Восточная Европа"
  },
  {
    "name": "Молдавия",
    "fullname": "Республика Молдова",
    "english": "Moldova",
    "capital": "Кининёв",
    "capital-en": "",
    "alpha2": "MD",
    "alpha3": "MDA",
    "iso": "498",
    "location": "Европа",
    "location-precise": "Восточная Европа"
  },
  {
    "name": "Дания",
    "fullname": "Королевство Дания",
    "english": "Denmark",
    "capital": "Копенгаген",
    "capital-en": "",
    "alpha2": "DK",
    "alpha3": "DNK",
    "iso": "208",
    "location": "Европа",
    "location-precise": "Северная Европа"
  },
  {
    "name": "Португалия",
    "fullname": "Португальская Республика",
    "english": "Portugal",
    "capital": "Лиссабон",
    "capital-en": "",
    "alpha2": "PT",
    "alpha3": "PRT",
    "iso": "620",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Великобритания",
    "fullname": "Соединенное Королевство Великобритании и Северной Ирландии",
    "english": "United Kingdom",
    "capital": "Лондон",
    "capital-en": "",
    "alpha2": "GB",
    "alpha3": "GBR",
    "iso": "826",
    "location": "Европа",
    "location-precise": "Северная Европа"
  },
  {
    "name": "Словения",
    "fullname": "Республика Словения",
    "english": "Slovenia",
    "capital": "Любляна",
    "capital-en": "",
    "alpha2": "SI",
    "alpha3": "SVN",
    "iso": "705",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Люксембург",
    "fullname": "Великое Герцогство Люксембург",
    "english": "Luxembourg",
    "capital": "Люксембург",
    "capital-en": "",
    "alpha2": "LU",
    "alpha3": "LUX",
    "iso": "442",
    "location": "Европа",
    "location-precise": "Западная Европа"
  },
  {
    "name": "Испания",
    "fullname": "Королевство Испания",
    "english": "Spain",
    "capital": "Мадрид",
    "capital-en": "",
    "alpha2": "ES",
    "alpha3": "ESP",
    "iso": "724",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Беларусь",
    "fullname": "Республика Беларусь",
    "english": "Belarus",
    "capital": "Минск",
    "capital-en": "",
    "alpha2": "BY",
    "alpha3": "BLR",
    "iso": "112",
    "location": "Европа",
    "location-precise": "Восточная Европа"
  },
  {
    "name": "Монако",
    "fullname": "Княжество Монако",
    "english": "Monaco",
    "capital": "Монако",
    "capital-en": "",
    "alpha2": "MC",
    "alpha3": "MCO",
    "iso": "492",
    "location": "Европа",
    "location-precise": "Западная Европа"
  },
  {
    "name": "Россия",
    "fullname": "Российская Федерация",
    "english": "Russian Federation",
    "capital": "Москва",
    "capital-en": "",
    "alpha2": "RU",
    "alpha3": "RUS",
    "iso": "643",
    "location": "Европа",
    "location-precise": "Восточная Европа"
  },
  {
    "name": "Норвегия",
    "fullname": "Королевство Норвегия",
    "english": "Norway",
    "capital": "Осло",
    "capital-en": "",
    "alpha2": "NO",
    "alpha3": "NOR",
    "iso": "578",
    "location": "Европа",
    "location-precise": "Северная Европа"
  },
  {
    "name": "Франция",
    "fullname": "Французская Республика",
    "english": "France",
    "capital": "Париж",
    "capital-en": "",
    "alpha2": "FR",
    "alpha3": "FRA",
    "iso": "250",
    "location": "Европа",
    "location-precise": "Западная Европа"
  },
  {
    "name": "Черногория",
    "fullname": "Республика Черногория",
    "english": "Montenegro",
    "capital": "Подгорица",
    "capital-en": "",
    "alpha2": "ME",
    "alpha3": "MNE",
    "iso": "499",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Чехия",
    "fullname": "Чешская Республика",
    "english": "Czech Republic",
    "capital": "Прага",
    "capital-en": "",
    "alpha2": "CZ",
    "alpha3": "CZE",
    "iso": "203",
    "location": "Европа",
    "location-precise": "Восточная Европа"
  },
  {
    "name": "Исландия",
    "fullname": "Республика Исландия",
    "english": "Iceland",
    "capital": "Рейкьявик",
    "capital-en": "",
    "alpha2": "IS",
    "alpha3": "ISL",
    "iso": "352",
    "location": "Европа",
    "location-precise": "Северная Европа"
  },
  {
    "name": "Латвия",
    "fullname": "Латвийская Республика",
    "english": "Latvia",
    "capital": "Рига",
    "capital-en": "",
    "alpha2": "LV",
    "alpha3": "LVA",
    "iso": "428",
    "location": "Европа",
    "location-precise": "Северная Европа"
  },
  {
    "name": "Италия",
    "fullname": "Итальянская Республика",
    "english": "Italy",
    "capital": "Рим",
    "capital-en": "",
    "alpha2": "IT",
    "alpha3": "ITA",
    "iso": "380",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Сан-Марино",
    "fullname": "Республика Сан-Марино",
    "english": "San Marino",
    "capital": "Сан-Марино",
    "capital-en": "",
    "alpha2": "SM",
    "alpha3": "SMR",
    "iso": "674",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Босния и\nГерцеговина",
    "fullname": " ",
    "english": "Bosnia and Herzegovina",
    "capital": "Сараево",
    "capital-en": "",
    "alpha2": "BA",
    "alpha3": "BIH",
    "iso": "070",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Македония",
    "fullname": "Республика Македония",
    "english": "Macedonia, The Former Yugoslav Republic Of",
    "capital": "Скопье",
    "capital-en": "",
    "alpha2": "MK",
    "alpha3": "MKD",
    "iso": "807",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Болгария",
    "fullname": "Республика Болгария",
    "english": "Bulgaria",
    "capital": "София",
    "capital-en": "",
    "alpha2": "BG",
    "alpha3": "BGR",
    "iso": "100",
    "location": "Европа",
    "location-precise": "Восточная Европа"
  },
  {
    "name": "Швеция",
    "fullname": "Королевство Швеция",
    "english": "Sweden",
    "capital": "Стокгольм",
    "capital-en": "",
    "alpha2": "SE",
    "alpha3": "SWE",
    "iso": "752",
    "location": "Европа",
    "location-precise": "Северная Европа"
  },
  {
    "name": "Эстония",
    "fullname": "Эстонская Республика",
    "english": "Estonia",
    "capital": "Таллин",
    "capital-en": "",
    "alpha2": "EE",
    "alpha3": "EST",
    "iso": "233",
    "location": "Европа",
    "location-precise": "Северная Европа"
  },
  {
    "name": "Албания",
    "fullname": "Республика Албания",
    "english": "Albania",
    "capital": "Тирана",
    "capital-en": "",
    "alpha2": "AL",
    "alpha3": "ALB",
    "iso": "008",
    "location": "Европа",
    "location-precise": "Южная Европа"
  },
  {
    "name": "Финляндия",
    "fullname": "Финляндская Республика",
    "english": "Finland",
    "capital": "Хельсинки",
    "capital-en": "",
    "alpha2": "FI",
    "alpha3": "FIN",
    "iso": "246",
    "location": "Европа",
    "location-precise": "Северная Европа"
  },
  {
    "name": "ОАЭ",
    "fullname": "Объединенные Арабские Эмираты",
    "english": "United Arab Emirates",
    "capital": "Абу-Даби",
    "capital-en": "",
    "alpha2": "AE",
    "alpha3": "ARE",
    "iso": "784",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Иордания",
    "fullname": "Иорданское Хашимитское Королевство",
    "english": "Jordan",
    "capital": "Амман",
    "capital-en": "",
    "alpha2": "JO",
    "alpha3": "JOR",
    "iso": "400",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Турция",
    "fullname": "Турецкая Республика",
    "english": "Turkey",
    "capital": "Анкара",
    "capital-en": "",
    "alpha2": "TR",
    "alpha3": "TUR",
    "iso": "792",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Казахстан",
    "fullname": "Республика Казахстан",
    "english": "Kazakhstan",
    "capital": "Астана",
    "capital-en": "",
    "alpha2": "KZ",
    "alpha3": "KAZ",
    "iso": "398",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Туркмения",
    "fullname": "Туркменистан",
    "english": "Turkmenistan",
    "capital": "Ашхабад",
    "capital-en": "",
    "alpha2": "TM",
    "alpha3": "TKM",
    "iso": "795",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Ирак",
    "fullname": "Республика Ирак",
    "english": "Iraq",
    "capital": "Багдад",
    "capital-en": "",
    "alpha2": "IQ",
    "alpha3": "IRQ",
    "iso": "368",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Азербайджан",
    "fullname": "Республика Азербайджан",
    "english": "Azerbaijan",
    "capital": "Баку",
    "capital-en": "",
    "alpha2": "AZ",
    "alpha3": "AZE",
    "iso": "031",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Таиланд",
    "fullname": "Королевство Таиланд",
    "english": "Thailand",
    "capital": "Бангкок",
    "capital-en": "",
    "alpha2": "TH",
    "alpha3": "THA",
    "iso": "764",
    "location": "Азия",
    "location-precise": "Юго-Восточная Азия"
  },
  {
    "name": "Бруней",
    "fullname": "Бруней-Даруссалам",
    "english": "Brunei Darussalam",
    "capital": "Бандар-Сери-Бегаван",
    "capital-en": "",
    "alpha2": "BN",
    "alpha3": "BRN",
    "iso": "096",
    "location": "Азия",
    "location-precise": "Юго-Восточная Азия"
  },
  {
    "name": "Ливан",
    "fullname": "Ливанская Республика",
    "english": "Lebanon",
    "capital": "Бейрут",
    "capital-en": "",
    "alpha2": "LB",
    "alpha3": "LBN",
    "iso": "422",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Киргизия",
    "fullname": "Киргизская Республика",
    "english": "Kyrgyzstan",
    "capital": "Бишкек",
    "capital-en": "",
    "alpha2": "KG",
    "alpha3": "KGZ",
    "iso": "417",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Лаос",
    "fullname": "Лаосская Народно-Демократическая Республика",
    "english": "Lao People's Democratic Republic",
    "capital": "Вьентьян",
    "capital-en": "",
    "alpha2": "LA",
    "alpha3": "LAO",
    "iso": "418",
    "location": "Азия",
    "location-precise": "Юго-Восточная Азия"
  },
  {
    "name": "Бангладеш",
    "fullname": "Народная Республика Бангладеш",
    "english": "Bangladesh",
    "capital": "Дакка",
    "capital-en": "",
    "alpha2": "BD",
    "alpha3": "BGD",
    "iso": "050",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Сирия",
    "fullname": "Сирийская Арабская Республика",
    "english": "Syrian Arab Republic",
    "capital": "Дамаск",
    "capital-en": "",
    "alpha2": "SY",
    "alpha3": "SYR",
    "iso": "760",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Индия",
    "fullname": "Республика Индия",
    "english": "India",
    "capital": "Дели",
    "capital-en": "",
    "alpha2": "IN",
    "alpha3": "IND",
    "iso": "356",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Индонезия",
    "fullname": "Республика Индонезия",
    "english": "Indonesia",
    "capital": "Джакарта",
    "capital-en": "",
    "alpha2": "ID",
    "alpha3": "IDN",
    "iso": "360",
    "location": "Азия",
    "location-precise": "Юго-Восточная Азия"
  },
  {
    "name": "Восточный\nТимор",
    "fullname": "Демократическая Республика Тимор-Лесте",
    "english": "Timor-Leste",
    "capital": "Дили",
    "capital-en": "",
    "alpha2": "TL",
    "alpha3": "TLS",
    "iso": "626",
    "location": "Азия",
    "location-precise": "Юго-Восточная Азия"
  },
  {
    "name": "Катар",
    "fullname": "Государство Катар",
    "english": "Qatar",
    "capital": "Доха",
    "capital-en": "",
    "alpha2": "QA",
    "alpha3": "QAT",
    "iso": "634",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Таджикистан",
    "fullname": "Республика Таджикистан",
    "english": "Tajikistan",
    "capital": "Душанбе",
    "capital-en": "",
    "alpha2": "TJ",
    "alpha3": "TJK",
    "iso": "762",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Армения",
    "fullname": "Республика Армения",
    "english": "Armenia",
    "capital": "Ереван",
    "capital-en": "",
    "alpha2": "AM",
    "alpha3": "ARM",
    "iso": "051",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Израиль",
    "fullname": "Государство Израиль",
    "english": "Israel",
    "capital": "Иерусалим",
    "capital-en": "",
    "alpha2": "IL",
    "alpha3": "ISR",
    "iso": "376",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Пакистан",
    "fullname": "Исламская Республика Пакистан",
    "english": "Pakistan",
    "capital": "Исламабад",
    "capital-en": "",
    "alpha2": "PK",
    "alpha3": "PAK",
    "iso": "586",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Афганистан",
    "fullname": "Переходное Исламское Государство Афганистан",
    "english": "Afghanistan",
    "capital": "Кабул",
    "capital-en": "",
    "alpha2": "AF",
    "alpha3": "AFG",
    "iso": "004",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Непал",
    "fullname": "Федеративная Демократическая Республика Непал",
    "english": "Nepal",
    "capital": "Катманду",
    "capital-en": "",
    "alpha2": "NP",
    "alpha3": "NPL",
    "iso": "524",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Малайзия",
    "fullname": " ",
    "english": "Malaysia",
    "capital": "Куала-Лумпур",
    "capital-en": "",
    "alpha2": "MY",
    "alpha3": "MYS",
    "iso": "458",
    "location": "Азия",
    "location-precise": "Юго-Восточная Азия"
  },
  {
    "name": "Мальдивы",
    "fullname": "Мальдивская Республика",
    "english": "Maldives",
    "capital": "Мале",
    "capital-en": "",
    "alpha2": "MV",
    "alpha3": "MDV",
    "iso": "462",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Бахрейн",
    "fullname": "Королевство Бахрейн",
    "english": "Bahrain",
    "capital": "Манама",
    "capital-en": "",
    "alpha2": "BH",
    "alpha3": "BHR",
    "iso": "048",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Филиппины",
    "fullname": "Республика Филиппины",
    "english": "Philippines",
    "capital": "Манила",
    "capital-en": "",
    "alpha2": "PH",
    "alpha3": "PHL",
    "iso": "608",
    "location": "Азия",
    "location-precise": "Юго-Восточная Азия"
  },
  {
    "name": "Оман",
    "fullname": "Султанат Оман",
    "english": "Oman",
    "capital": "Маскат",
    "capital-en": "",
    "alpha2": "OM",
    "alpha3": "OMN",
    "iso": "512",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Мьянма",
    "fullname": "Союз Мьянма",
    "english": "Myanmar",
    "capital": "Нейпьидо",
    "capital-en": "",
    "alpha2": "MM",
    "alpha3": "MMR",
    "iso": "104",
    "location": "Азия",
    "location-precise": "Юго-Восточная Азия"
  },
  {
    "name": "Кипр",
    "fullname": "Республика Кипр",
    "english": "Cyprus",
    "capital": "Никосия",
    "capital-en": "",
    "alpha2": "CY",
    "alpha3": "CYP",
    "iso": "196",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Китай",
    "fullname": "Китайская Народная Республика",
    "english": "China",
    "capital": "Пекин",
    "capital-en": "",
    "alpha2": "CN",
    "alpha3": "CHN",
    "iso": "156",
    "location": "Азия",
    "location-precise": "Восточная Азия"
  },
  {
    "name": "Камбоджа",
    "fullname": "Королевство Камбоджа",
    "english": "Cambodia",
    "capital": "Пномпень",
    "capital-en": "",
    "alpha2": "KH",
    "alpha3": "KHM",
    "iso": "116",
    "location": "Азия",
    "location-precise": "Юго-Восточная Азия"
  },
  {
    "name": "КНДР",
    "fullname": "Корейская Народно-Демократическая Республика",
    "english": "Korea, Democratic People's republic of",
    "capital": "Пхеньян",
    "capital-en": "",
    "alpha2": "KP",
    "alpha3": "PRK",
    "iso": "408",
    "location": "Азия",
    "location-precise": "Восточная Азия"
  },
  {
    "name": "Йемен",
    "fullname": "Йеменская Республика",
    "english": "Yemen",
    "capital": "Сана",
    "capital-en": "",
    "alpha2": "YE",
    "alpha3": "YEM",
    "iso": "887",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Республика\nКорея",
    "fullname": "Республика Корея",
    "english": "Korea, Republic of",
    "capital": "Сеул",
    "capital-en": "",
    "alpha2": "KR",
    "alpha3": "KOR",
    "iso": "410",
    "location": "Азия",
    "location-precise": "Восточная Азия"
  },
  {
    "name": "Сингапур",
    "fullname": "Республика Сингапур",
    "english": "Singapore",
    "capital": "Сингапур",
    "capital-en": "",
    "alpha2": "SG",
    "alpha3": "SGP",
    "iso": "702",
    "location": "Азия",
    "location-precise": "Юго-Восточная Азия"
  },
  {
    "name": "Узбекистан",
    "fullname": "Республика Узбекистан",
    "english": "Uzbekistan",
    "capital": "Ташкент",
    "capital-en": "",
    "alpha2": "UZ",
    "alpha3": "UZB",
    "iso": "860",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Грузия",
    "fullname": " ",
    "english": "Georgia",
    "capital": "Тбилиси",
    "capital-en": "",
    "alpha2": "GE",
    "alpha3": "GEO",
    "iso": "268",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Иран",
    "fullname": "Исламская Республика Иран",
    "english": "Iran, Islamic Republic of",
    "capital": "Тегеран",
    "capital-en": "",
    "alpha2": "IR",
    "alpha3": "IRN",
    "iso": "364",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Япония",
    "fullname": " ",
    "english": "Japan",
    "capital": "Токио",
    "capital-en": "",
    "alpha2": "JP",
    "alpha3": "JPN",
    "iso": "392",
    "location": "Азия",
    "location-precise": "Восточная Азия"
  },
  {
    "name": "Бутан",
    "fullname": "Королевство Бутан",
    "english": "Bhutan",
    "capital": "Тхимпху",
    "capital-en": "",
    "alpha2": "BT",
    "alpha3": "BTN",
    "iso": "064",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Монголия",
    "fullname": " ",
    "english": "Mongolia",
    "capital": "Улан-Батор",
    "capital-en": "",
    "alpha2": "MN",
    "alpha3": "MNG",
    "iso": "496",
    "location": "Азия",
    "location-precise": "Восточная Азия"
  },
  {
    "name": "Вьетнам",
    "fullname": "Социалистическая Республика Вьетнам",
    "english": "Vietnam",
    "capital": "Ханой",
    "capital-en": "",
    "alpha2": "VN",
    "alpha3": "VNM",
    "iso": "704",
    "location": "Азия",
    "location-precise": "Юго-Восточная Азия"
  },
  {
    "name": "Шри-Ланка",
    "fullname": "Демократическая Социалистическая Республика Шри-Ланка",
    "english": "Sri Lanka",
    "capital": "Шри-Джаяварденепура-Котте",
    "capital-en": "",
    "alpha2": "LK",
    "alpha3": "LKA",
    "iso": "144",
    "location": "Азия",
    "location-precise": "Южная часть Центральной Азии"
  },
  {
    "name": "Кувейт",
    "fullname": "Государство Кувейт",
    "english": "Kuwait",
    "capital": "Эль-Кувейт",
    "capital-en": "",
    "alpha2": "KW",
    "alpha3": "KWT",
    "iso": "414",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Саудовская\nАравия",
    "fullname": "Королевство Саудовская Аравия",
    "english": "Saudi Arabia",
    "capital": "Эр-Рияд",
    "capital-en": "",
    "alpha2": "SA",
    "alpha3": "SAU",
    "iso": "682",
    "location": "Азия",
    "location-precise": "Западная Азия"
  },
  {
    "name": "Нигерия",
    "fullname": "Федеративная Республика Нигерия",
    "english": "Nigeria",
    "capital": "Абуджа",
    "capital-en": "",
    "alpha2": "NG",
    "alpha3": "NGA",
    "iso": "566",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Эфиопия",
    "fullname": "Федеративная Демократическая Республика Эфиопия",
    "english": "Ethiopia",
    "capital": "Аддис-Абеба",
    "capital-en": "",
    "alpha2": "ET",
    "alpha3": "ETH",
    "iso": "231",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Гана",
    "fullname": "Республика Гана",
    "english": "Ghana",
    "capital": "Аккра",
    "capital-en": "",
    "alpha2": "GH",
    "alpha3": "GHA",
    "iso": "288",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Алжир",
    "fullname": "Алжирская Народная Демократическая Республика",
    "english": "Algeria",
    "capital": "Алжир",
    "capital-en": "",
    "alpha2": "DZ",
    "alpha3": "DZA",
    "iso": "012",
    "location": "Африка",
    "location-precise": "Северная Африка"
  },
  {
    "name": "Мадагаскар",
    "fullname": "Республика Мадагаскар",
    "english": "Madagascar",
    "capital": "Антананариву",
    "capital-en": "",
    "alpha2": "MG",
    "alpha3": "MDG",
    "iso": "450",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Эритрея",
    "fullname": " ",
    "english": "Eritrea",
    "capital": "Асмэра",
    "capital-en": "",
    "alpha2": "ER",
    "alpha3": "ERI",
    "iso": "232",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Мали",
    "fullname": "Республика Мали",
    "english": "Mali",
    "capital": "Бамако",
    "capital-en": "",
    "alpha2": "ML",
    "alpha3": "MLI",
    "iso": "466",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "ЦАР",
    "fullname": "Центрально-Африканская Республика",
    "english": "Central African Republic",
    "capital": "Банги",
    "capital-en": "",
    "alpha2": "CF",
    "alpha3": "CAF",
    "iso": "140",
    "location": "Африка",
    "location-precise": "Центральная Африка"
  },
  {
    "name": "Гамбия",
    "fullname": "Республика Гамбия",
    "english": "Gambia",
    "capital": "Банжул",
    "capital-en": "",
    "alpha2": "GM",
    "alpha3": "GMB",
    "iso": "270",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Гвинея",
    "fullname": "Гвинейская Республика",
    "english": "Guinea",
    "capital": "Конакри",
    "capital-en": "",
    "alpha2": "GN",
    "alpha3": "GIN",
    "iso": "324",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Гвинея-Бисау",
    "fullname": "Республика Гвинея-Бисау",
    "english": "Guinea-Bissau",
    "capital": "Бисау",
    "capital-en": "",
    "alpha2": "GW",
    "alpha3": "GNB",
    "iso": "624",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Конго",
    "fullname": "Республика Конго",
    "english": "Congo",
    "capital": "Браззавиль",
    "capital-en": "",
    "alpha2": "CG",
    "alpha3": "COG",
    "iso": "178",
    "location": "Африка",
    "location-precise": "Центральная Африка"
  },
  {
    "name": "Конго,\nДем. Респ.",
    "fullname": "Демократическая Республика Конго",
    "english": "Congo, Democratic Republic of the",
    "capital": "Киншаса",
    "capital-en": "",
    "alpha2": "CD",
    "alpha3": "COD",
    "iso": "180",
    "location": "Африка",
    "location-precise": "Центральная Африка"
  },
  {
    "name": "Бурунди",
    "fullname": "Республика Бурунди",
    "english": "Burundi",
    "capital": "Бужумбура",
    "capital-en": "",
    "alpha2": "BI",
    "alpha3": "BDI",
    "iso": "108",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Сейшелы",
    "fullname": "Республика Сейшелы",
    "english": "Seychelles",
    "capital": "Виктория",
    "capital-en": "",
    "alpha2": "SC",
    "alpha3": "SYC",
    "iso": "690",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Намибия",
    "fullname": "Республика Намибия",
    "english": "Namibia",
    "capital": "Виндхук",
    "capital-en": "",
    "alpha2": "NA",
    "alpha3": "NAM",
    "iso": "516",
    "location": "Африка",
    "location-precise": "Южная часть Африки"
  },
  {
    "name": "Ботсвана",
    "fullname": "Республика Ботсвана",
    "english": "Botswana",
    "capital": "Габороне",
    "capital-en": "",
    "alpha2": "BW",
    "alpha3": "BWA",
    "iso": "072",
    "location": "Африка",
    "location-precise": "Южная часть Африки"
  },
  {
    "name": "Сенегал",
    "fullname": "Республика Сенегал",
    "english": "Senegal",
    "capital": "Дакар",
    "capital-en": "",
    "alpha2": "SN",
    "alpha3": "SEN",
    "iso": "686",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Джибути",
    "fullname": "Республика Джибути",
    "english": "Djibouti",
    "capital": "Джибути",
    "capital-en": "",
    "alpha2": "DJ",
    "alpha3": "DJI",
    "iso": "262",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Южный Судан",
    "fullname": " ",
    "english": "South Sudan",
    "capital": "Джуба",
    "capital-en": "",
    "alpha2": "SS",
    "alpha3": "SSD",
    "iso": "728",
    "location": "Африка",
    "location-precise": "Северная Африка"
  },
  {
    "name": "Танзания",
    "fullname": "Объединенная Республика Танзания",
    "english": "Tanzania, United Republic Of",
    "capital": "Додома",
    "capital-en": "",
    "alpha2": "TZ",
    "alpha3": "TZA",
    "iso": "834",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Египет",
    "fullname": "Арабская Республика Египет",
    "english": "Egypt",
    "capital": "Каир",
    "capital-en": "",
    "alpha2": "EG",
    "alpha3": "EGY",
    "iso": "818",
    "location": "Африка",
    "location-precise": "Северная Африка"
  },
  {
    "name": "Уганда",
    "fullname": "Республика Уганда",
    "english": "Uganda",
    "capital": "Кампала",
    "capital-en": "",
    "alpha2": "UG",
    "alpha3": "UGA",
    "iso": "800",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Руанда",
    "fullname": "Руандийская Республика",
    "english": "Rwanda",
    "capital": "Кигали",
    "capital-en": "",
    "alpha2": "RW",
    "alpha3": "RWA",
    "iso": "646",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Габон",
    "fullname": "Габонская Республика",
    "english": "Gabon",
    "capital": "Либревиль",
    "capital-en": "",
    "alpha2": "GA",
    "alpha3": "GAB",
    "iso": "266",
    "location": "Африка",
    "location-precise": "Центральная Африка"
  },
  {
    "name": "Малави",
    "fullname": "Республика Малави",
    "english": "Malawi",
    "capital": "Лилонгве",
    "capital-en": "",
    "alpha2": "MW",
    "alpha3": "MWI",
    "iso": "454",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Того",
    "fullname": "Тоголезская Республика",
    "english": "Togo",
    "capital": "Ломе",
    "capital-en": "",
    "alpha2": "TG",
    "alpha3": "TGO",
    "iso": "768",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Ангола",
    "fullname": "Республика Ангола",
    "english": "Angola",
    "capital": "Луанда",
    "capital-en": "",
    "alpha2": "AO",
    "alpha3": "AGO",
    "iso": "024",
    "location": "Африка",
    "location-precise": "Центральная Африка"
  },
  {
    "name": "Замбия",
    "fullname": "Республика Замбия",
    "english": "Zambia",
    "capital": "Лусака",
    "capital-en": "",
    "alpha2": "ZM",
    "alpha3": "ZMB",
    "iso": "894",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Экваториальная\nГвинея",
    "fullname": "Республика Экваториальная Гвинея",
    "english": "Equatorial Guinea",
    "capital": "Малабо",
    "capital-en": "",
    "alpha2": "GQ",
    "alpha3": "GNQ",
    "iso": "226",
    "location": "Африка",
    "location-precise": "Центральная Африка"
  },
  {
    "name": "Мозамбик",
    "fullname": "Республика Мозамбик",
    "english": "Mozambique",
    "capital": "Мапуту",
    "capital-en": "",
    "alpha2": "MZ",
    "alpha3": "MOZ",
    "iso": "508",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Лесото",
    "fullname": "Королевство Лесото",
    "english": "Lesotho",
    "capital": "Масеру",
    "capital-en": "",
    "alpha2": "LS",
    "alpha3": "LSO",
    "iso": "426",
    "location": "Африка",
    "location-precise": "Южная часть Африки"
  },
  {
    "name": "Свазиленд",
    "fullname": "Королевство Свазиленд",
    "english": "Swaziland",
    "capital": "Мбабане",
    "capital-en": "",
    "alpha2": "SZ",
    "alpha3": "SWZ",
    "iso": "748",
    "location": "Африка",
    "location-precise": "Южная часть Африки"
  },
  {
    "name": "Сомали",
    "fullname": "Сомалийская Республика",
    "english": "Somalia",
    "capital": "Могадишо",
    "capital-en": "",
    "alpha2": "SO",
    "alpha3": "SOM",
    "iso": "706",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Либерия",
    "fullname": "Республика Либерия",
    "english": "Liberia",
    "capital": "Монровия",
    "capital-en": "",
    "alpha2": "LR",
    "alpha3": "LBR",
    "iso": "430",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Коморы",
    "fullname": "Союз Коморы",
    "english": "Comoros",
    "capital": "Морони",
    "capital-en": "",
    "alpha2": "KM",
    "alpha3": "COM",
    "iso": "174",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Кения",
    "fullname": "Республика Кения",
    "english": "Kenya",
    "capital": "Найроби",
    "capital-en": "",
    "alpha2": "KE",
    "alpha3": "KEN",
    "iso": "404",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Чад",
    "fullname": "Республика Чад",
    "english": "Chad",
    "capital": "Нджамена",
    "capital-en": "",
    "alpha2": "TD",
    "alpha3": "TCD",
    "iso": "148",
    "location": "Африка",
    "location-precise": "Центральная Африка"
  },
  {
    "name": "Нигер",
    "fullname": "Республика Нигер",
    "english": "Niger",
    "capital": "Ниамей",
    "capital-en": "",
    "alpha2": "NE",
    "alpha3": "NER",
    "iso": "562",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Мавритания",
    "fullname": "Исламская Республика Мавритания",
    "english": "Mauritania",
    "capital": "Нуакшот",
    "capital-en": "",
    "alpha2": "MR",
    "alpha3": "MRT",
    "iso": "478",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Маврикий",
    "fullname": "Республика Маврикий",
    "english": "Mauritius",
    "capital": "Порт-Луи",
    "capital-en": "",
    "alpha2": "MU",
    "alpha3": "MUS",
    "iso": "480",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Бенин",
    "fullname": "Республика Бенин",
    "english": "Benin",
    "capital": "Порто-Ново",
    "capital-en": "",
    "alpha2": "BJ",
    "alpha3": "BEN",
    "iso": "204",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Кабо-Верде",
    "fullname": "Республика Кабо-Верде",
    "english": "Cape Verde",
    "capital": "Прая",
    "capital-en": "",
    "alpha2": "CV",
    "alpha3": "CPV",
    "iso": "132",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "ЮАР",
    "fullname": "Южно-Африканская Республика",
    "english": "South Africa",
    "capital": "Претория",
    "capital-en": "",
    "alpha2": "ZA",
    "alpha3": "ZAF",
    "iso": "710",
    "location": "Африка",
    "location-precise": "Южная часть Африки"
  },
  {
    "name": "Марокко",
    "fullname": "Королевство Марокко",
    "english": "Morocco",
    "capital": "Рабат",
    "capital-en": "",
    "alpha2": "MA",
    "alpha3": "MAR",
    "iso": "504",
    "location": "Африка",
    "location-precise": "Северная Африка"
  },
  {
    "name": "Сан-Томе и\nПринсипи",
    "fullname": "Демократическая Республика Сан-Томе и Принсипи",
    "english": "Sao Tome and Principe",
    "capital": "Сан-Томе",
    "capital-en": "",
    "alpha2": "ST",
    "alpha3": "STP",
    "iso": "678",
    "location": "Африка",
    "location-precise": "Центральная Африка"
  },
  {
    "name": "Ливия",
    "fullname": "",
    "english": "",
    "capital": "Триполи",
    "capital-en": "",
    "alpha2": "",
    "alpha3": "",
    "iso": "",
    "location": "Африка",
    "location-precise": "Северная Африка"
  },
  {
    "name": "Тунис",
    "fullname": "Тунисская Республика",
    "english": "Tunisia",
    "capital": "Тунис",
    "capital-en": "",
    "alpha2": "TN",
    "alpha3": "TUN",
    "iso": "788",
    "location": "Африка",
    "location-precise": "Северная Африка"
  },
  {
    "name": "Буркина-Фасо",
    "fullname": " ",
    "english": "Burkina Faso",
    "capital": "Уагадугу",
    "capital-en": "",
    "alpha2": "BF",
    "alpha3": "BFA",
    "iso": "854",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Сьерра-Леоне",
    "fullname": "Республика Сьерра-Леоне",
    "english": "Sierra Leone",
    "capital": "Фритаун",
    "capital-en": "",
    "alpha2": "SL",
    "alpha3": "SLE",
    "iso": "694",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Зимбабве",
    "fullname": "Республика Зимбабве",
    "english": "Zimbabwe",
    "capital": "Хараре",
    "capital-en": "",
    "alpha2": "ZW",
    "alpha3": "ZWE",
    "iso": "716",
    "location": "Африка",
    "location-precise": "Восточная Африка"
  },
  {
    "name": "Судан",
    "fullname": "Республика Судан",
    "english": "Sudan",
    "capital": "Хартум",
    "capital-en": "",
    "alpha2": "SD",
    "alpha3": "SDN",
    "iso": "736",
    "location": "Африка",
    "location-precise": "Северная Африка"
  },
  {
    "name": "Кот д'Ивуар",
    "fullname": "Республика Кот д'Ивуар",
    "english": "Cote d'Ivoire",
    "capital": "Ямусукро",
    "capital-en": "",
    "alpha2": "CI",
    "alpha3": "CIV",
    "iso": "384",
    "location": "Африка",
    "location-precise": "Западная Африка"
  },
  {
    "name": "Камерун",
    "fullname": "Республика Камерун",
    "english": "Cameroon",
    "capital": "Яунде",
    "capital-en": "",
    "alpha2": "CM",
    "alpha3": "CMR",
    "iso": "120",
    "location": "Африка",
    "location-precise": "Центральная Африка"
  },
  {
    "name": "Парагвай",
    "fullname": "Республика Парагвай",
    "english": "Paraguay",
    "capital": "Асунсьон",
    "capital-en": "",
    "alpha2": "PY",
    "alpha3": "PRY",
    "iso": "600",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "Сент-Китс\nи Невис",
    "fullname": " ",
    "english": "Saint Kitts and Nevis",
    "capital": "Бастер",
    "capital-en": "",
    "alpha2": "KN",
    "alpha3": "KNA",
    "iso": "659",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Белиз",
    "fullname": " ",
    "english": "Belize",
    "capital": "Бельмопан",
    "capital-en": "",
    "alpha2": "BZ",
    "alpha3": "BLZ",
    "iso": "084",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Колумбия",
    "fullname": "Республика Колумбия",
    "english": "Colombia",
    "capital": "Богота",
    "capital-en": "",
    "alpha2": "CO",
    "alpha3": "COL",
    "iso": "170",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "Бразилия",
    "fullname": "Федеративная Республика Бразилия",
    "english": "Brazil",
    "capital": "Бразилиа",
    "capital-en": "",
    "alpha2": "BR",
    "alpha3": "BRA",
    "iso": "076",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "Барбадос",
    "fullname": " ",
    "english": "Barbados",
    "capital": "Бриджтаун",
    "capital-en": "",
    "alpha2": "BB",
    "alpha3": "BRB",
    "iso": "052",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Аргентина",
    "fullname": "Аргентинская Республика",
    "english": "Argentina",
    "capital": "Буэнос-Айрес",
    "capital-en": "",
    "alpha2": "AR",
    "alpha3": "ARG",
    "iso": "032",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "США",
    "fullname": "Соединенные Штаты Америки",
    "english": "United States",
    "capital": "Вашингтон",
    "capital-en": "",
    "alpha2": "US",
    "alpha3": "USA",
    "iso": "840",
    "location": "Америка",
    "location-precise": "Северная Америка"
  },
  {
    "name": "Куба",
    "fullname": "Республика Куба",
    "english": "Cuba",
    "capital": "Гавана",
    "capital-en": "",
    "alpha2": "CU",
    "alpha3": "CUB",
    "iso": "192",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Гватемала",
    "fullname": "Республика Гватемала",
    "english": "Guatemala",
    "capital": "Гватемала",
    "capital-en": "",
    "alpha2": "GT",
    "alpha3": "GTM",
    "iso": "320",
    "location": "Америка",
    "location-precise": "Центральная Америка"
  },
  {
    "name": "Гайана",
    "fullname": "Республика Гайана",
    "english": "Guyana",
    "capital": "Джорджтаун",
    "capital-en": "",
    "alpha2": "GY",
    "alpha3": "GUY",
    "iso": "328",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "Венесуэла",
    "fullname": "Боливарийская Республика Венесуэла",
    "english": "Venezuela",
    "capital": "Каракас",
    "capital-en": "",
    "alpha2": "VE",
    "alpha3": "VEN",
    "iso": "862",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "Сент-Люсия",
    "fullname": " ",
    "english": "Saint Lucia",
    "capital": "Кастри",
    "capital-en": "",
    "alpha2": "LC",
    "alpha3": "LCA",
    "iso": "662",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Сент-Винсент\nи Гренадины",
    "fullname": " ",
    "english": "Saint Vincent and the Grenadines",
    "capital": "Кингстаун",
    "capital-en": "",
    "alpha2": "VC",
    "alpha3": "VCT",
    "iso": "670",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Ямайка",
    "fullname": " ",
    "english": "Jamaica",
    "capital": "Кингстон",
    "capital-en": "",
    "alpha2": "JM",
    "alpha3": "JAM",
    "iso": "388",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Эквадор",
    "fullname": "Республика Эквадор",
    "english": "Ecuador",
    "capital": "Кито",
    "capital-en": "",
    "alpha2": "EC",
    "alpha3": "ECU",
    "iso": "218",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "Перу",
    "fullname": "Республика Перу",
    "english": "Peru",
    "capital": "Лима",
    "capital-en": "",
    "alpha2": "PE",
    "alpha3": "PER",
    "iso": "604",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "Никарагуа",
    "fullname": "Республика Никарагуа",
    "english": "Nicaragua",
    "capital": "Манагуа",
    "capital-en": "",
    "alpha2": "NI",
    "alpha3": "NIC",
    "iso": "558",
    "location": "Америка",
    "location-precise": "Центральная Америка"
  },
  {
    "name": "Мексика",
    "fullname": "Мексиканские Соединенные Штаты",
    "english": "Mexico",
    "capital": "Мехико",
    "capital-en": "",
    "alpha2": "MX",
    "alpha3": "MEX",
    "iso": "484",
    "location": "Америка",
    "location-precise": "Центральная Америка"
  },
  {
    "name": "Уругвай",
    "fullname": "Восточная Республика Уругвай",
    "english": "Uruguay",
    "capital": "Монтевидео",
    "capital-en": "",
    "alpha2": "UY",
    "alpha3": "URY",
    "iso": "858",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "Багамы",
    "fullname": "Содружество Багамы",
    "english": "Bahamas",
    "capital": "Нассау",
    "capital-en": "",
    "alpha2": "BS",
    "alpha3": "BHS",
    "iso": "044",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Канада",
    "fullname": " ",
    "english": "Canada",
    "capital": "Оттава",
    "capital-en": "",
    "alpha2": "CA",
    "alpha3": "CAN",
    "iso": "124",
    "location": "Америка",
    "location-precise": "Северная Америка"
  },
  {
    "name": "Панама",
    "fullname": "Республика Панама",
    "english": "Panama",
    "capital": "Панама",
    "capital-en": "",
    "alpha2": "PA",
    "alpha3": "PAN",
    "iso": "591",
    "location": "Америка",
    "location-precise": "Центральная Америка"
  },
  {
    "name": "Суринам",
    "fullname": "Республика Суринам",
    "english": "Suriname",
    "capital": "Парамарибо",
    "capital-en": "",
    "alpha2": "SR",
    "alpha3": "SUR",
    "iso": "740",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "Гаити",
    "fullname": "Республика Гаити",
    "english": "Haiti",
    "capital": "Порт-о-Пренс",
    "capital-en": "",
    "alpha2": "HT",
    "alpha3": "HTI",
    "iso": "332",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Тринидад\nи Тобаго",
    "fullname": "Республика Тринидад и Тобаго",
    "english": "Trinidad and Tobago",
    "capital": "Порт-оф-Спейн",
    "capital-en": "",
    "alpha2": "TT",
    "alpha3": "TTO",
    "iso": "780",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Доминика",
    "fullname": "Содружество Доминики",
    "english": "Dominica",
    "capital": "Розо",
    "capital-en": "",
    "alpha2": "DM",
    "alpha3": "DMA",
    "iso": "212",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Сальвадор",
    "fullname": "Республика Эль-Сальвадор",
    "english": "El Salvador",
    "capital": "Сан-Сальвадор",
    "capital-en": "",
    "alpha2": "SV",
    "alpha3": "SLV",
    "iso": "222",
    "location": "Америка",
    "location-precise": "Центральная Америка"
  },
  {
    "name": "Коста-Рика",
    "fullname": "Республика Коста-Рика",
    "english": "Costa Rica",
    "capital": "Сан-Хосе",
    "capital-en": "",
    "alpha2": "CR",
    "alpha3": "CRI",
    "iso": "188",
    "location": "Америка",
    "location-precise": "Центральная Америка"
  },
  {
    "name": "Доминиканская\nРеспублика",
    "fullname": " ",
    "english": "Dominican Republic",
    "capital": "Розо",
    "capital-en": "",
    "alpha2": "DO",
    "alpha3": "DOM",
    "iso": "214",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Чили",
    "fullname": "Республика Чили",
    "english": "Chile",
    "capital": "Сантьяго",
    "capital-en": "",
    "alpha2": "CL",
    "alpha3": "CHL",
    "iso": "152",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "Антигуа\nи Барбуда",
    "fullname": " ",
    "english": "Antigua and Barbuda",
    "capital": "Сент-Джонс",
    "capital-en": "",
    "alpha2": "AG",
    "alpha3": "ATG",
    "iso": "028",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Гренада",
    "fullname": " ",
    "english": "Grenada",
    "capital": "Сент-Джорджес",
    "capital-en": "",
    "alpha2": "GD",
    "alpha3": "GRD",
    "iso": "308",
    "location": "Америка",
    "location-precise": "Карибский бассейн"
  },
  {
    "name": "Боливия",
    "fullname": "Многонациональное Государство Боливия",
    "english": "Bolivia, plurinational state of",
    "capital": "Сукре",
    "capital-en": "",
    "alpha2": "BO",
    "alpha3": "BOL",
    "iso": "068",
    "location": "Америка",
    "location-precise": "Южная Америка"
  },
  {
    "name": "Гондурас",
    "fullname": "Республика Гондурас",
    "english": "Honduras",
    "capital": "Тегусигальпа",
    "capital-en": "",
    "alpha2": "HN",
    "alpha3": "HND",
    "iso": "340",
    "location": "Америка",
    "location-precise": "Центральная Америка"
  },
  {
    "name": "Самоа",
    "fullname": "Независимое Государство Самоа",
    "english": "Samoa",
    "capital": "Апиа",
    "capital-en": "",
    "alpha2": "WS",
    "alpha3": "WSM",
    "iso": "882",
    "location": "Океания",
    "location-precise": "Полинезия"
  },
  {
    "name": "Новая Зеландия",
    "fullname": " ",
    "english": "New Zealand",
    "capital": "Веллингтон",
    "capital-en": "",
    "alpha2": "NZ",
    "alpha3": "NZL",
    "iso": "554",
    "location": "Океания",
    "location-precise": "Австралия и Новая Зеландия"
  },
  {
    "name": "Австралия",
    "fullname": " ",
    "english": "Australia",
    "capital": "Канберра",
    "capital-en": "",
    "alpha2": "AU",
    "alpha3": "AUS",
    "iso": "036",
    "location": "Океания",
    "location-precise": "Австралия и Новая Зеландия"
  },
  {
    "name": "Маршалловы\nострова",
    "fullname": "Республика Маршалловы острова",
    "english": "Marshall Islands",
    "capital": "Маджуро",
    "capital-en": "",
    "alpha2": "MH",
    "alpha3": "MHL",
    "iso": "584",
    "location": "Океания",
    "location-precise": "Микронезия"
  },
  {
    "name": "Палау",
    "fullname": "Республика Палау",
    "english": "Palau",
    "capital": "Нгерулмуд",
    "capital-en": "",
    "alpha2": "PW",
    "alpha3": "PLW",
    "iso": "585",
    "location": "Океания",
    "location-precise": "Микронезия"
  },
  {
    "name": "Тонга",
    "fullname": "Королевство Тонга",
    "english": "Tonga",
    "capital": "Нукуалофа",
    "capital-en": "",
    "alpha2": "TO",
    "alpha3": "TON",
    "iso": "776",
    "location": "Океания",
    "location-precise": "Полинезия"
  },
  {
    "name": "Микронезия",
    "fullname": "Федеративные штаты Микронезии",
    "english": "Micronesia, Federated States of",
    "capital": "Паликир",
    "capital-en": "",
    "alpha2": "FM",
    "alpha3": "FSM",
    "iso": "583",
    "location": "Океания",
    "location-precise": "Микронезия"
  },
  {
    "name": "Вануату",
    "fullname": "Республика Вануату",
    "english": "Vanuatu",
    "capital": "Порт-Вила",
    "capital-en": "",
    "alpha2": "VU",
    "alpha3": "VUT",
    "iso": "548",
    "location": "Океания",
    "location-precise": "Меланезия"
  },
  {
    "name": "Папуа-Новая\nГвинея",
    "fullname": " ",
    "english": "Papua New Guinea",
    "capital": "Порт-Морсби",
    "capital-en": "",
    "alpha2": "PG",
    "alpha3": "PNG",
    "iso": "598",
    "location": "Океания",
    "location-precise": "Меланезия"
  },
  {
    "name": "Фиджи",
    "fullname": "Республика островов Фиджи",
    "english": "Fiji",
    "capital": "Сува",
    "capital-en": "",
    "alpha2": "FJ",
    "alpha3": "FJI",
    "iso": "242",
    "location": "Океания",
    "location-precise": "Меланезия"
  },
  {
    "name": "Тувалу",
    "fullname": " ",
    "english": "Tuvalu",
    "capital": "Фунафути",
    "capital-en": "",
    "alpha2": "TV",
    "alpha3": "TUV",
    "iso": "798",
    "location": "Океания",
    "location-precise": "Полинезия"
  },
  {
    "name": "Соломоновы\nострова",
    "fullname": " ",
    "english": "Solomon Islands",
    "capital": "Хониара",
    "capital-en": "",
    "alpha2": "SB",
    "alpha3": "SLB",
    "iso": "090",
    "location": "Океания",
    "location-precise": "Меланезия"
  },
  {
    "name": "Кирибати",
    "fullname": "Республика Кирибати",
    "english": "Kiribati",
    "capital": "Южная Тарава",
    "capital-en": "",
    "alpha2": "KI",
    "alpha3": "KIR",
    "iso": "296",
    "location": "Океания",
    "location-precise": "Микронезия"
  },
  {
    "name": "Науру",
    "fullname": "Республика Науру",
    "english": "Nauru",
    "capital": "Офиц. столицы нет",
    "capital-en": "",
    "alpha2": "NR",
    "alpha3": "NRU",
    "iso": "520",
    "location": "Океания",
    "location-precise": "Микронезия"
  },
];
